### ISSUE TITLE
User Profile -> Email Notifications returns an error page

### ISSUE THREAD

**Issue by tieniber** [mendix/mxforum#20]
See screenshot below. Most critical issue is that the link under "Search View the current issue of the status of, or report new bug." points to http://cnprog.uservoice.com/

![capture](https://cloud.githubusercontent.com/assets/3960619/12201115/7982fcc4-b5f0-11e5-8119-f1c7cfff1327.PNG)

**Comment by Achiel** [comment]
Fixed the critical issue, still looking at fixing Email Notifications link

**Comment by Achiel** [comment]
Fixed!
